OPENAI_API_KEY: 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
TOKEN: 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
